### ISSUE TITLE
google_mobility.R

### ISSUE THREAD

**Issue by jjcortes** [nicholasdavies/newcovid#1]
Hi,

This file is missing.

googmo = fread("~/Dropbox/uk_covid_data/fitting/data/Global_Mobility_Report-2020-12-27.csv");

Best wishes.

**Comment by nicholasdavies** [comment]
We don't upload this file because it's 200+ MB, but if you download the
"global CSV" from https://www.google.com/covid19/mobility/, that's it.

Thanks,

Nick

**Comment by jjcortes** [comment]
Thank you very much.

**Comment by nicholasdavies** [comment]
Marking this as closed now, thanks @jjcortes. I have tried to indicate in the code where files are either downloadable elsewhere or not available because we can't share them, but have not yet looked extensively for everywhere this is the case. If the code loads something from "uk_covid_data_sensitive" then it is not shareable. If the code loads something from my "Downloads" folder, many of these are mapping files produced by the ONS and should be obtainable by searching for the file name.
